services: 
  postgres: 
    image: postgres
    volumes:
      - ./inid-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "admin@123"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin@123"
    ports:
      - "9000:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge